{
  description = "My Valheim server";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    valheim-nix = {
      url = "github:XavierYounan/valheim_nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, valheim-nix, ... }: {
    nixosConfigurations.valheim = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        valheim-nix.nixosModules.default
        ./hardware-configuration.nix # generated by nixos-generate-config; see the runbook
        ./configuration.nix
      ];
    };
  };
}
